# Generated by Django 4.1 on 2023-12-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('cell_phone', models.CharField(max_length=20, verbose_name='Telefone celular')),
                ('service', models.CharField(choices=[('P', 'Pé'), ('M', 'Mão'), ('C', 'Corte Cabelo'), ('T', 'Todos')], max_length=1, verbose_name='Serviço')),
                ('worker', models.CharField(choices=[('S', 'Simone'), ('E', 'Elvira'), ('L', 'Laura'), ('P', 'Pietra')], max_length=1, verbose_name='Profissional')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['id'],
            },
        ),
    ]
