# Generated by Django 4.1 on 2023-12-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='service',
            field=models.CharField(max_length=50, verbose_name='Serviço'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='worker',
            field=models.CharField(max_length=50, verbose_name='Profissional'),
        ),
    ]
